/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventsystem;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author lulu
 */
public class EventSystemGUI extends javax.swing.JFrame {

    
    EventSystem e = new EventSystem();
    private static List<EventSystem> list=new ArrayList<EventSystem> ();
    boolean end=false;
    /**
     * Creates new form EventSystemGUI
     */
    public EventSystemGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupTypeEvent = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Text1 = new javax.swing.JLabel();
        ON = new javax.swing.JRadioButton();
        OFF = new javax.swing.JRadioButton();
        Text2 = new javax.swing.JLabel();
        TextField1 = new javax.swing.JTextField();
        Send = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Text1.setText("Seleccione el tipo de evento:");

        GroupTypeEvent.add(ON);
        ON.setText("ON");
        ON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ONMouseClicked(evt);
            }
        });

        GroupTypeEvent.add(OFF);
        OFF.setText("OFF");
        OFF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OFFMouseClicked(evt);
            }
        });

        Text2.setText("Introduzca el nombre del dispositivo:");

        Send.setText("Enviar");
        Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendActionPerformed(evt);
            }
        });

        Exit.setText("Salir");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(ON)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OFF))
                        .addComponent(Text1))
                    .addComponent(Text2)
                    .addComponent(TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Send)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Text1)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OFF)
                    .addComponent(ON))
                .addGap(18, 18, 18)
                .addComponent(Text2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Send)
                    .addComponent(Exit))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ONMouseClicked
        // TODO add your handling code here:
        e.setEventType(ON.getLabel());
        System.out.print("Click ON:"+ON.getLabel()+"\n");
     //   System.out.print("\n"+ e.toString());
    }//GEN-LAST:event_ONMouseClicked

    private void OFFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OFFMouseClicked
        // TODO add your handling code here:
        e.setEventType(OFF.getLabel());
        System.out.print("Click ON:"+OFF.getLabel()+"\n");
        //System.out.print("\n"+ e.toString());
    }//GEN-LAST:event_OFFMouseClicked

    private void SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendActionPerformed
        // TODO add your handling code here:
        if(e.getEventType()==null){
            JOptionPane.showMessageDialog(null, "No ha seleccionado el tipo de evento.");
        }
        e.setDeviceName(TextField1.getText());
        if(TextField1.getText().equals("")){
            JOptionPane.showMessageDialog(TextField1, "No ha introducido el nombre del dispositivo.");
        }
        else{
                System.out.print("Click Text:"+e.getDeviceName()+"\n");
       // System.out.print("\n"+ e.toString());  
                EventSystem2GUI event2 = new EventSystem2GUI();
               // while(end != true){
                if(e.getEventType() == "ON"){

                             list=e.EventOn(e.getEventType(), e.getDeviceName(), list);
                             System.out.print("Resultados en memoria:"+ list.toString()+"\n");
                             setVisible(false);
                             event2.showdata(list);
                             event2.setVisible(true);


                }
                if(e.getEventType() == "OFF"){

                             list=e.EventOff(e.getEventType(), e.getDeviceName(), list);
                             System.out.print("Resultados en memoria:"+ list.toString()+"\n");
                             setVisible(false);
                             event2.showdata(list);
                             event2.setVisible(true);         
                }
        }
  


    }//GEN-LAST:event_SendActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
       // end=true;
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EventSystemGUI event = new EventSystemGUI();
                //event.add(e);
                //event.getContentPane().add(new JPanel());
                event.setVisible(true);
           
            }
        });
        //EventSystemGUI 
       // String input_typeEvent= EventSystemGUI.
        /* while(input_typeEvent.equals("ON") || input_typeEvent.equals("OFF")){
         
         }*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.ButtonGroup GroupTypeEvent;
    private javax.swing.JRadioButton OFF;
    private javax.swing.JRadioButton ON;
    private javax.swing.JButton Send;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JTextField TextField1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
